server:
  undertow:
    accesslog:
      enabled: true

spring:
  thymeleaf:
    cache: false

  jpa:
      database: H2

  datasource:
      url: jdbc:h2:./pub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driverClassName: org.h2.Driver

